import Link from "next/link";
import {
  ArrowRight,
  Database,
  Download,
  GaugeCircle,
  ShieldCheck,
  Sparkles,
  Workflow,
  Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { TiltCard } from "@/components/tilt-card";
import { DashboardMockup } from "@/components/dashboard-mockup";
import { CountUp } from "@/components/count-up";
import { Hero3DMount } from "@/components/hero-3d-mount";
import { ChatWidget } from "@/components/chat-widget";

export default function LandingPage() {
  return (
    <main className="relative min-h-screen overflow-hidden bg-black text-white">
      {/* === Hero === */}
      <section className="relative isolate min-h-[100vh] overflow-hidden">
        <div className="absolute inset-0">
          <Hero3DMount />
        </div>
        {/* Dark gradient to keep text readable over 3D */}
        <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/40 via-black/30 to-black" />
        <div className="pointer-events-none absolute inset-0 gradient-mesh opacity-60" />

        <header className="relative z-10">
          <div className="container flex items-center justify-between py-6">
            <div className="flex items-center gap-2">
              <div className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 text-white shadow-lg shadow-blue-500/30">
                <Sparkles className="h-4 w-4" />
              </div>
              <span className="text-lg font-semibold tracking-tight">Readiness</span>
            </div>
            <nav className="hidden items-center gap-8 text-sm text-white/60 md:flex">
              <a href="#features" className="hover:text-white">Features</a>
              <a href="#how" className="hover:text-white">How it works</a>
              <a href="#pricing" className="hover:text-white">Pricing</a>
            </nav>
            <div className="flex items-center gap-2">
              <Button asChild variant="ghost" className="text-white hover:bg-white/10">
                <Link href="/login">Sign in</Link>
              </Button>
              <Button
                asChild
                className="bg-white text-black shadow-lg shadow-white/10 hover:bg-white/90"
              >
                <Link href="/signup">
                  Get started <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
            </div>
          </div>
        </header>

        <div className="relative z-10 container flex min-h-[calc(100vh-100px)] flex-col items-center justify-center text-center">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1 text-xs text-white/70 backdrop-blur">
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400" />
            Now scanning Databricks · Snowflake · Unity Catalog
          </div>
          <h1 className="max-w-4xl text-balance text-5xl font-semibold tracking-tight md:text-7xl">
            Know if your data is{" "}
            <span className="bg-gradient-to-r from-blue-400 via-fuchsia-400 to-cyan-300 bg-clip-text text-transparent">
              actually ready for AI.
            </span>
          </h1>
          <p className="mt-6 max-w-2xl text-pretty text-lg text-white/70 md:text-xl">
            Connect your warehouse, get a 0–100 readiness score, and a prioritized
            roadmap to unlock RAG, agents, and analytics — generated by Claude over
            your live catalog.
          </p>
          <div className="mt-10 flex flex-col gap-3 sm:flex-row">
            <Button
              asChild
              size="lg"
              className="bg-white text-black shadow-2xl shadow-white/20 hover:bg-white/90"
            >
              <Link href="/signup">
                Start a scan <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
            <Button
              asChild
              size="lg"
              variant="outline"
              className="border-white/20 bg-white/5 text-white backdrop-blur hover:bg-white/10"
            >
              <Link href="/login">See live demo</Link>
            </Button>
            <Button
              asChild
              size="lg"
              variant="ghost"
              className="text-white/70 hover:bg-white/5 hover:text-white"
            >
              <a href="/api/brochure" download>
                <Download className="h-4 w-4" /> Download overview
              </a>
            </Button>
          </div>
          <div className="mt-16 text-xs uppercase tracking-widest text-white/30">
            Scroll to explore
          </div>
        </div>
      </section>

      {/* === Trust strip === */}
      <section className="relative border-y border-white/5 bg-black/50">
        <div className="container py-10">
          <div className="text-center text-xs uppercase tracking-[0.25em] text-white/40">
            Built for the modern data stack
          </div>
          <div className="mt-6 flex flex-wrap items-center justify-center gap-x-12 gap-y-4 text-white/60">
            {[
              "Databricks",
              "Snowflake",
              "Unity Catalog",
              "Delta Lake",
              "Iceberg",
              "dbt",
              "Airflow",
            ].map((name) => (
              <span
                key={name}
                className="text-lg font-semibold tracking-tight transition-colors hover:text-white"
              >
                {name}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* === Stats === */}
      <section className="relative border-b border-white/5">
        <div className="container py-24">
          <div className="grid grid-cols-2 gap-8 md:grid-cols-4">
            {[
              { value: 100, suffix: "+", label: "checks per scan" },
              { value: 12, suffix: "k", label: "tables analyzed in minutes" },
              { value: 60, suffix: "%", label: "PII coverage gap, on average" },
              { value: 10, suffix: "x", label: "faster than manual audits" },
            ].map((s) => (
              <div key={s.label}>
                <div className="text-5xl font-semibold tracking-tight md:text-6xl">
                  <CountUp to={s.value} />
                  <span className="bg-gradient-to-r from-blue-400 to-fuchsia-400 bg-clip-text text-transparent">
                    {s.suffix}
                  </span>
                </div>
                <div className="mt-2 text-sm text-white/50">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* === Dashboard mockup === */}
      <section id="how" className="relative border-b border-white/5">
        <div className="absolute inset-x-0 top-0 -z-10 h-96 gradient-mesh opacity-40" />
        <div className="container py-32">
          <div className="mx-auto max-w-3xl text-center">
            <div className="text-xs uppercase tracking-[0.25em] text-blue-400">
              The Report
            </div>
            <h2 className="mt-4 text-balance text-4xl font-semibold tracking-tight md:text-5xl">
              See exactly where your platform stands.
            </h2>
            <p className="mt-4 text-white/60">
              Six pillars, scored 0–100. Specific findings tied to real tables.
              Prioritized fixes with effort estimates — exportable to Jira in one
              click.
            </p>
          </div>
          <div className="mt-16">
            <DashboardMockup />
          </div>
        </div>
      </section>

      {/* === Features (mouse-tilt cards) === */}
      <section id="features" className="relative border-b border-white/5">
        <div className="container py-32">
          <div className="mx-auto max-w-3xl text-center">
            <div className="text-xs uppercase tracking-[0.25em] text-fuchsia-400">
              What you get
            </div>
            <h2 className="mt-4 text-balance text-4xl font-semibold tracking-tight md:text-5xl">
              Catalog-aware. Governance-first. Roadmap-ready.
            </h2>
          </div>

          <div className="mt-16 grid grid-cols-1 gap-6 md:grid-cols-3">
            {[
              {
                icon: Database,
                title: "Catalog-aware scanning",
                body: "Walks Unity Catalog, ACCOUNT_USAGE, dbt manifest, and Delta storage to understand what you actually have — not what was last documented.",
              },
              {
                icon: ShieldCheck,
                title: "Governance, not theatre",
                body: "Detects untagged PII, masking gaps, and lineage holes that block AI features in regulated industries — before you ship.",
              },
              {
                icon: Workflow,
                title: "Prioritized roadmap",
                body: "Not just a score: ranked recommendations with effort estimates, owner suggestions, and one-click export to Jira or Linear.",
              },
              {
                icon: Sparkles,
                title: "Claude-generated narrative",
                body: "Executive-ready summaries written by Claude over your inventory snapshot. No prompt engineering required.",
              },
              {
                icon: GaugeCircle,
                title: "RAG readiness score",
                body: "Identifies high-value text columns, missing vector indices, and chunking gaps that quietly tank retrieval quality.",
              },
              {
                icon: Zap,
                title: "Pluggable connectors",
                body: "Databricks, Snowflake, mock data — same API. New sources added monthly. Self-hosted for regulated workloads.",
              },
            ].map((f) => (
              <TiltCard key={f.title}>
                <div className="grid h-9 w-9 place-items-center rounded-lg bg-gradient-to-br from-blue-500/30 to-purple-500/30 text-blue-300">
                  <f.icon className="h-4 w-4" />
                </div>
                <h3 className="mt-4 text-lg font-medium">{f.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-white/60">
                  {f.body}
                </p>
              </TiltCard>
            ))}
          </div>
        </div>
      </section>

      {/* === Final CTA === */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 -z-10 gradient-mesh opacity-80" />
        <div className="container py-32">
          <div className="relative mx-auto max-w-4xl overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-blue-600/20 via-purple-600/10 to-cyan-500/20 p-12 text-center backdrop-blur-xl md:p-16">
            <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-500/20 via-transparent to-transparent" />
            <h2 className="text-balance text-4xl font-semibold tracking-tight md:text-5xl">
              Get your first AI Readiness Report in under 10 minutes.
            </h2>
            <p className="mt-4 text-white/70">
              Free during private beta. No credit card. Mock data available — bring
              your warehouse when you&apos;re ready.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
              <Button
                asChild
                size="lg"
                className="bg-white text-black shadow-2xl shadow-white/20 hover:bg-white/90"
              >
                <Link href="/signup">
                  Start free <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
              <Button
                asChild
                size="lg"
                variant="outline"
                className="border-white/20 bg-white/5 text-white hover:bg-white/10"
              >
                <Link href="/login">Watch a demo</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Floating product chatbot — landing page only */}
      <ChatWidget />

      {/* === Footer === */}
      <footer className="border-t border-white/5">
        <div className="container flex flex-col items-center justify-between gap-4 py-8 text-sm text-white/40 md:flex-row">
          <div className="flex items-center gap-2">
            <div className="grid h-6 w-6 place-items-center rounded-md bg-gradient-to-br from-blue-500 to-purple-600">
              <Sparkles className="h-3 w-3" />
            </div>
            <span>© {new Date().getFullYear()} Readiness</span>
          </div>
          <div className="flex gap-6">
            <Link href="/docs" className="hover:text-white">Docs</Link>
            <a href="/api/brochure" className="hover:text-white" download>One-pager</a>
            <Link href="/login" className="hover:text-white">Sign in</Link>
            <a href="#" className="hover:text-white">Privacy</a>
            <a href="#" className="hover:text-white">Terms</a>
          </div>
        </div>
      </footer>
    </main>
  );
}
